# Libraries
import os
import argparse
import configparser
import shutil

# Modules
import core
from config import maidDir, maidTempDir, maidConfDir, appPath

confHeader = """# File generated by Maid - DO NOT EDIT
"""

# Global variable


def FirstTimeSetup():

    print("Running First-Time-Setup")

    cwd = os.getcwd()

    # Maid config.maidDir
    if not os.path.isdir(maidConfDir):
        os.mkdir(maidConfDir)
    os.chdir(maidConfDir)
    print(f"Config directory: {os.getcwd()}")

    # Config file
    config = configparser.ConfigParser()
    config['options'] = {
        'rootDir': os.fsdecode(maidDir),
        'confDir': os.fsdecode(maidConfDir),
        'tempDir': os.fsdecode(maidTempDir),
        'logFile': ''}
    with open(os.fsencode('maid.conf'), 'w') as configfile:
        configfile.write(confHeader)
        config.write(configfile)

    # TaskList file
    taskList = configparser.ConfigParser()
    taskList['list'] = {
        'GitPkg': 'False'}
    with open(os.fsencode('list.conf'), 'w') as taskfile:
        taskfile.write(confHeader)
        taskList.write(taskfile)

    # Pkg maidDir
    os.chdir(maidDir)
    if not os.path.isdir(maidDir):
        os.mkdir(maidDir)

    if not os.path.isdir('list/'):
        os.mkdir('list/')
    if not os.path.isdir('pkg/'):
        os.mkdir('pkg/')

    os.chdir(cwd)


def ReadConf():
    maidConfFile = os.fsencode(appPath + '\\maid\\maid.conf')
    exists = os.path.isfile(maidConfFile)
    if not exists:
        return False
    conf = configparser.ConfigParser()
    conf.read(maidConfFile)

    conf.maidDir = os.fsencode(conf['options']['rootDir'])
    conf.maidConfDir = os.fsencode(conf['options']['confDir'])
    conf.maidTempDir = os.fsencode(conf['options']['tempDir'])

    return True


parser = argparse.ArgumentParser(
    prog='Maid', description='Maid - Package Manager')
parser.add_argument('--version', action='version',
                    version='%(prog)s Pre-Alpha')
subparsers = parser.add_subparsers(
    help='sub-command help',
    title='command',
    required=True,
    metavar='<command>')
subparsers.add_parser('add', help='Add package')
subparsers.add_parser('rem', help='Remove package')

args = parser.parse_args()


if not ReadConf():
    FirstTimeSetup()

print('Maid root directory:', os.fsdecode(maidDir))
print('Maid config directory:', os.fsdecode(maidConfDir))
print('Maid temp directory:', os.fsdecode(maidTempDir))
