# Libraries
import os
import argparse
import configparser
import shutil

# Modules
import core
import config

confHeader = """# File generated by Maid - DO NOT EDIT
"""

# Global variable


def FirstTimeSetup():

    print("Running First-Time-Setup")

    cwd = os.getcwd()

    # Maid config.maidDir
    if not os.path.isdir(config.maidConfDir):
        os.mkdir(config.maidConfDir)
    os.chdir(config.maidConfDir)
    print(f"Config directory: {os.getcwd()}")

    # Config file
    config = configparser.ConfigParser()
    config['options'] = {
        'rootDir': os.fsdecode(config.maidDir),
        'confDir': os.fsdecode(config.maidConfDir),
        'tempDir': os.fsdecode(config.maidTempDir),
        'logFile': ''}
    with open(os.fsencode('maid.conf'), 'w') as configfile:
        configfile.write(confHeader)
        config.write(configfile)

    # TaskList file
    taskList = configparser.ConfigParser()
    taskList['list'] = {
        'GitPkg': 'False'}
    with open(os.fsencode('list.conf'), 'w') as taskfile:
        taskfile.write(confHeader)
        taskList.write(taskfile)

    # Pkg config.maidDir
    os.chdir(config.maidDir)
    if not os.path.isdir(config.maidDir):
        os.mkdir(config.maidDir)

    if not os.path.isdir('list/'):
        os.mkdir('list/')
    if not os.path.isdir('pkg/'):
        os.mkdir('pkg/')

    os.chdir(cwd)


parser = argparse.ArgumentParser(
    prog='Maid', description='Maid - Package Manager')
parser.add_argument('--version', action='version',
                    version='%(prog)s Pre-Alpha')


def ReadConf():
    maidConfFile = os.fsencode(config.appPath + '\\maid\\maid.conf')
    exists = os.path.isfile(maidConfFile)
    if not exists:
        return False
    conf = configparser.ConfigParser()
    conf.read(maidConfFile)

    conf.maidDir = os.fsencode(conf['options']['rootDir'])
    conf.maidConfDir = os.fsencode(conf['options']['confDir'])
    conf.maidTempDir = os.fsencode(conf['options']['tempDir'])

    return True


args = parser.parse_args()

if not ReadConf():
    FirstTimeSetup()

print('Maid root directory:', os.fsdecode(config.maidDir))
print('Maid config directory:', os.fsdecode(config.maidConfDir))
print('Maid temp directory:', os.fsdecode(config.maidTempDir))
